[package]
name = "bourg_model"
version = "0.1.0"
authors = ["chaddw <caw14f@my.fsu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.20"